spring:
  datasource:
    url: jdbc:sqlite:db.sqlite3
    driverClassName: org.sqlite.JDBC
    username: admin
    password: admin
    initializationMode: always

  jpa:
    databasePlatform: sqliteproject.SQLDialect
    hibernate:
      ddlAuto: create-drop
